### ISSUE TITLE
StopIteration Error in auto_solve.py example

### ISSUE THREAD

**Issue by Aniell4** [h0nde/py-hcaptcha#3]
Exception in thread Thread-47:                                                                                          
Traceback (most recent call last):                                                                                        
File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner                                                     
self.run()                                                                                                            
File "/usr/lib/python3.8/threading.py", line 870, in run                                                                  
self._target(*self._args, **self._kwargs)                                                                             
File "captcha_solver.py", line 37, in thread_func                                                                         
proxy = next(proxies)                                                                                               
StopIteration                                                                                                           
Traceback (most recent call last):                                                                                        
File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner                                                     
self.run()                                                                                                            
File "/usr/lib/python3.8/threading.py", line 870, in run                                                                  
self._target(*self._args, **self._kwargs)                                                                             
File "captcha_solver.py", line 37, in thread_func                                                                         
proxy = next(proxies)                                                                                               
StopIteration                                                                                                               
self.run()                                                                                                            
File "/usr/lib/python3.8/threading.py", line 870, in run                                                                  
self._target(*self._args, **self._kwargs)                                                                             
File "captcha_solver.py", line 37, in thread_func                                                                         
proxy = next(proxies)                                                                                               
StopIteration                                                                                                               
self._target(*self._args, **self._kwargs)                                                                             
File "captcha_solver.py", line 37, in thread_func                                                                         
proxy = next(proxies)                                                                                               
StopIteration

**Comment by Mak365-hash** [comment]
Means you have no proxies
